### ISSUE TITLE
Travis output looks weird

### ISSUE THREAD

**Issue by bebraw** [calvinmetcalf/tap-nyan#1]
Just thought to mention that Travis output looks a little weird. Example: https://travis-ci.org/annojs/generate/builds/47631924 .

This might not be an issue in the tool itself. Maybe it is possible to work around outside of it.

**Comment by calvinmetcalf** [comment]
Yeah I don't think it likes that tty output the mocha dot reporter looks
pretty bad toi

**Comment by Sceat** [comment]
any ETA for a wrokaround since 2015 ? lol

**Comment by calvinmetcalf** [comment]
yes, don't use in travis, more fundamentally travis output is a stream/log, which is different from the tty type interface in your console, so you can't just erase stuff from travis all you can do is output more logs lines

**Comment by Sceat** [comment]
i'm so sad, miss the nyan :c

**Comment by bebraw** [comment]
Let's close this one since there's no way to fix this for Travis.
