### ISSUE TITLE
Output does not show when used as a npm script

### ISSUE THREAD

**Issue by BerkeleyTrue** [calvinmetcalf/tap-nyan#2]
![1__tmux](https://cloud.githubusercontent.com/assets/6775919/10872521/8a170ec6-80b8-11e5-9e61-6eb665feba40.png)

node 4.2.1
npm 2.14.7

**Comment by calvinmetcalf** [comment]
glad I could help

**Comment by BerkeleyTrue** [comment]
:shipit:
